"""add soc and health columns

Revision ID: 0c5132a6a9ae
Revises: a0ead1910c13
Create Date: 2025-08-08 13:41:35.362471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c5132a6a9ae'
down_revision = 'a0ead1910c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_data_bms_002')
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.drop_column('health')
        batch_op.drop_column('soc')

    op.create_table('battery_data_bms_002',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('soc', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature', mysql.FLOAT(), nullable=False),
    sa.Column('voltage', mysql.FLOAT(), nullable=False),
    sa.Column('current', mysql.FLOAT(), nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=False),
    sa.Column('lon', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
