"""change battery_info id column types

Revision ID: 28d030dbaff2
Revises: 67fd856d7fd0
Create Date: 2025-09-25 15:52:20.009302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28d030dbaff2'
down_revision = '67fd856d7fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.alter_column('esp_id',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('root_id',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.alter_column('root_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('esp_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
