"""change lat, lon fields

Revision ID: 382b52a29ab2
Revises: 6986ae27e8ae
Create Date: 2025-05-28 15:13:33.005906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '382b52a29ab2'
down_revision = '6986ae27e8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
