"""add battery tables

Revision ID: 6986ae27e8ae
Revises: eca0eeb83db4
Create Date: 2025-05-21 16:10:52.357554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6986ae27e8ae'
down_revision = 'eca0eeb83db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('online_status', sa.Enum('online', 'offline', name='onlinestatusenum'), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['battery_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_info')
    # ### end Alembic commands ###
