"""initial migration

Revision ID: 95531688264c
Revises: 
Create Date: 2025-06-03 14:32:19.011779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95531688264c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('online_status', sa.Enum('online', 'offline', name='onlinestatusenum'), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['battery_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_info')
    # ### end Alembic commands ###
