"""Initial migration

Revision ID: a0ead1910c13
Revises: 
Create Date: 2025-07-02 10:35:19.217886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0ead1910c13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("battery_info",
    sa.Column("id", sa.String(length=64), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("temperature", sa.Float(), nullable=True),
    sa.Column("voltage", sa.Float(), nullable=True),
    sa.Column("last_updated_time", sa.DateTime(), nullable=False),
    sa.Column("lat", sa.Float(), nullable=True),
    sa.Column("lon", sa.Float(), nullable=True),
    sa.Column("parent_id", sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("role",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=80), nullable=True),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_table("user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("first_name", sa.String(length=255), nullable=False),
    sa.Column("last_name", sa.String(length=255), nullable=True),
    sa.Column("email", sa.String(length=255), nullable=False),
    sa.Column("password", sa.String(length=255), nullable=False),
    sa.Column("active", sa.Boolean(), nullable=True),
    sa.Column("confirmed_at", sa.DateTime(), nullable=True),
    sa.Column("fs_uniquifier", sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("fs_uniquifier")
    )
    op.create_table("roles_users",
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("role_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["role_id"], ["role.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("battery_info")
    # ### end Alembic commands ###
