"""add charge columns

Revision ID: e3cd1a90590b
Revises: a0ead1910c13
Create Date: 2025-08-14 10:11:19.438950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3cd1a90590b'
down_revision = 'a0ead1910c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_info', schema=None) as batch_op:
        batch_op.drop_column('charge')
    # ### end Alembic commands ###
