"""Initial migration

Revision ID: e655883b7bce
Revises: 
Create Date: 2025-06-03 15:47:08.084253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e655883b7bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('online_status', sa.Enum('online', 'offline', name='onlinestatusenum'), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lon_test', sa.Float(), nullable=True),
    sa.Column('lon_test_db', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_info')
    # ### end Alembic commands ###
