"""update user blueprint tables

Revision ID: 2c9e866f8c2e
Revises: e27d64d96b49
Create Date: 2025-08-27 15:49:27.432905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c9e866f8c2e"
down_revision = "e27d64d96b49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users")
    op.drop_table("user")
    op.drop_table("role")

    op.create_table("roles",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=80), nullable=True),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("first_name", sa.String(length=255), nullable=False),
    sa.Column("last_name", sa.String(length=255), nullable=True),
    sa.Column("email", sa.String(length=255), nullable=False),
    sa.Column("password", sa.String(length=255), nullable=False),
    sa.Column("active", sa.Boolean(), nullable=True),
    sa.Column("confirmed_at", sa.DateTime(), nullable=True),
    sa.Column("fs_uniquifier", sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("fs_uniquifier")
    )
    op.create_table("roles_users",
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("role_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
