"""initiate

Revision ID: 3439c6d78cbf
Revises: 
Create Date: 2025-08-19 16:38:58.544416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3439c6d78cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_info',
    sa.Column('esp_id', sa.String(length=7), nullable=False),
    sa.Column('root_id', sa.String(length=7), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('esp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_info')
    # ### end Alembic commands ###
