"""add live_websocket column

Revision ID: c2c752e5a5d7
Revises: 3439c6d78cbf
Create Date: 2025-08-20 14:15:11.521180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c2c752e5a5d7"
down_revision = "3439c6d78cbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("battery_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("live_websocket", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("battery_info", schema=None) as batch_op:
        batch_op.drop_column("live_websocket")
    # ### end Alembic commands ###
