"""add OTC and wifi to batetry_data_<esp_id> tables

Revision ID: e27d64d96b49
Revises: 70ef787c836c
Create Date: 2025-08-26 15:49:13.739944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27d64d96b49'
down_revision = '70ef787c836c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
