"""link batteries to users

Revision ID: 034282959bbd
Revises: f8dfd6a80e34
Create Date: 2026-01-14 12:05:15.391567

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "034282959bbd"
down_revision = "f8dfd6a80e34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("battery_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, "users", ["owner_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("battery_info", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###
