"""change column

Revision ID: 552e42731de2
Revises: d24b3b3b7c00
Create Date: 2026-01-20 17:16:02.084061

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "552e42731de2"
down_revision = "d24b3b3b7c00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prediction_features", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("capacity_Ah_last_50_cycles", sa.Float(), nullable=False)
        )
        batch_op.drop_column("charge_Ah_last_50_cycles")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prediction_features", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("charge_Ah_last_50_cycles", mysql.FLOAT(), nullable=False)
        )
        batch_op.drop_column("capacity_Ah_last_50_cycles")

    # ### end Alembic commands ###
