"""add table for model metadata

Revision ID: b2e847bdb6da
Revises: 5d8502cba9c5
Create Date: 2026-01-28 17:18:05.081967

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2e847bdb6da"
down_revision = "5d8502cba9c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_metadata",
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.String(length=255), nullable=False),
        sa.Column("creation_timestamp", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("model_name", "version", "storage_uri"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_metadata")
    # ### end Alembic commands ###
