"""unnecessary user column

Revision ID: d0c90bae08f0
Revises: 034282959bbd
Create Date: 2026-01-14 17:09:11.382601

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d0c90bae08f0"
down_revision = "034282959bbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("confirmed_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confirmed_at", mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
