"""add table for ML features

Revision ID: d24b3b3b7c00
Revises: d0c90bae08f0
Create Date: 2026-01-16 12:44:10.365003

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d24b3b3b7c00"
down_revision = "d0c90bae08f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prediction_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("esp_id", sa.Integer(), nullable=False),
        sa.Column("cycle_index", sa.Integer(), nullable=False),
        sa.Column("mean_temp_last_50_cycles", sa.Float(), nullable=False),
        sa.Column("mean_DoD_last_50_cycles", sa.Float(), nullable=False),
        sa.Column("charge_Ah_last_50_cycles", sa.Float(), nullable=False),
        sa.Column("capacity_slope_last_200_cycles", sa.Float(), nullable=False),
        sa.Column("hours_soc_gt_90_last_7d", sa.Float(), nullable=False),
        sa.Column("mean_temp_idle_last_7d", sa.Float(), nullable=False),
        sa.Column("idle_hours_last_7d", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prediction_features")
    # ### end Alembic commands ###
