"""add subscription column

Revision ID: f8dfd6a80e34
Revises: 28d030dbaff2
Create Date: 2025-12-19 17:17:48.242655

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8dfd6a80e34"
down_revision = "28d030dbaff2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subscribed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("subscribed")

    # ### end Alembic commands ###
